services:
  db:
    image: postgres:16.6
    restart: always
    container_name: postgres-db
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_DB: icfes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
      PGADMIN_LISTEN_PORT: 80
      DATABASE_HOST: db

    ports:
      - "80:80"
    depends_on:
      - db
    restart: always

  api: 
    build: 
      context: .
      dockerfile: api/Dockerfile
    container_name: node-api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: adminpass
      DB_NAME: icfes
    ports: 
      - "3000:3000"
    depends_on:
      - db
    restart: always

  #cliente: 
  #  build:
  #    context: .
  #    dockerfile: cliente/Dockerfile
  #  container_name: angular-cliente
  #  ports:
  #    - "4200:4200"
  #  volumes:
  #    - ./cliente:/app
  #  restart: always
  #  
volumes:
  postgres_data:

    

  
    


      
      