services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres-db
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_DB: icfes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
      PGADMIN_LISTEN_PORT: 80
      DATABASE_HOST: db
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - app-network

    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: node-api
    environment:
      # Database
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: adminpass
      DB_NAME: icfes
      # Runtime
      NODE_ENV: production
      # Keycloak
      KEYCLOAK_SERVER_URL: http://localhost:8080
      KEYCLOAK_CLIENT_ID: icfes-cli
      KEYCLOAK_REALM: icfes-realm
      KEYCLOAK_REALM_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArwgcXjDc38W8f0VwUQyObW2iNmZfsnGjLKOYP/E5e8/s08iRplXxn+kcQbI28P1f7TDleIY0L2nEBNhhUCqD4CsBbRENuadL5RI4pcvrLv9Grr5GopC4JC4eqsae2Eb0NnCNjf/jVKl8oIj3IZl09bGrc0J5JPCJpO7c8eYTIBY5eurHv0RQnj3v3OKKZX2tBZJJB2C8W8HdDc5/wdCCvIkmbmi6aMKY08A4PRiApWkf+3jzAERD2HI6MHULD0VEtnp1cOEbLdRpow21V0CgBIBf9J4otWH7+k/WrndGW4PMTlOivJ+fUBMdeo4eN38BThPusml1V6Wk1AKfWGzCFwIDAQAB
      KEYCLOAK_SECRET: xpq2ie28qDpgkSeoWlgWjHZEv6vvnCxb
      # Session
      SESSION_SECRET: secret-session-k24681357
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: sh -c "sleep 15 && exec npm start"
    networks:
      - app-network
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak_backup:/opt/keycloak/data/import
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: always 

  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3300:3000"  # 👈 aquí se cambia el puerto externo
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: admin
      MB_DB_PASS: adminpass
      MB_DB_HOST: db
    depends_on:
      - db 
    networks:
      - app-network

volumes:
  postgres_data:
  keycloak_data: 
networks:
  app-network:
    driver: bridge
