services:
  db:
    image: postgres:16.6
    restart: always
    container_name: postgres-db
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_DB: icfes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
      PGADMIN_LISTEN_PORT: 80
      DATABASE_HOST: db
      PGADMIN_CONNECTIONS: '[{"name": "PostgresDB", "host": "db", "port": 5432, "username": "admin", "password": "adminpass", "database": "icfes"}]'
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: node-api
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: adminpass
      DB_NAME: icfes
    env_file:
      - ./api/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: always
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
